services:
  tunnel-server:
    image: ghcr.io/findstr/tunnel:latest-server
    ports:
      - "8443:443"
    environment:
      - KEY=${KEY:-0000000000000000}
    restart: unless-stopped
    container_name: tunnel-server
